#!/bin/bash
# generate-favicons.sh
# Generates favicons from content/imgs/headshot.jpg into assets/
# Generated by Matthew Ward with ChatGPT :)

SRC="content/imgs/headshot.jpg"
DEST_DIR="assets/favicon"

# Make sure destination exists
mkdir -p "$DEST_DIR"

# Sizes for favicon.ico
convert "$SRC" -resize 16x16 "$DEST_DIR/favicon-16x16.png"
convert "$SRC" -resize 32x32 "$DEST_DIR/favicon-32x32.png"
convert "$SRC" -resize 48x48 "$DEST_DIR/favicon-48x48.png"

# Combine into favicon.ico
convert "$DEST_DIR/favicon-16x16.png" "$DEST_DIR/favicon-32x32.png" "$DEST_DIR/favicon-48x48.png" "$DEST_DIR/favicon.ico"

# Apple touch icon
convert "$SRC" -resize 180x180 "$DEST_DIR/apple-touch-icon.png"

# Android / web manifest icons
convert "$SRC" -resize 192x192 "$DEST_DIR/android-chrome-192x192.png"
convert "$SRC" -resize 512x512 "$DEST_DIR/android-chrome-512x512.png"

# Generate a basic site.webmanifest if it doesn't exist
MANIFEST="$DEST_DIR/site.webmanifest"
if [[ ! -f "$MANIFEST" ]]; then
  cat > "$MANIFEST" <<EOL
{
  "name": "Matthew Ward",
  "short_name": "Matthew Ward",
  "icons": [
    { "src": "/favicon-192x192.png", "sizes": "192x192", "type": "image/png" },
    { "src": "/favicon-512x512.png", "sizes": "512x512", "type": "image/png" }
  ],
  "start_url": "/",
  "display": "standalone",
  "theme_color": "#ffffff",
  "background_color": "#ffffff"
}
EOL
fi

echo "Favicons and manifest generated in $DEST_DIR"