#!/bin/bash
# inject-favicon.sh
# Usage: ./inject-favicon.sh path/to/index.html
# Generated by Matthew Ward with ChatGPT :)

INDEX_FILE="$1"
ASSETS_DIR="_site/assets/favicon"
SITE_ROOT="_site"

if [[ ! -f "$INDEX_FILE" ]]; then
  echo "Error: $INDEX_FILE does not exist"
  exit 1
fi

# Copy favicon.ico and any needed files to _site/ for default location
if [[ -d "$ASSETS_DIR" ]]; then
  cp -u "$ASSETS_DIR/favicon.ico" "$SITE_ROOT/"
  cp -u "$ASSETS_DIR/favicon-32x32.png" "$SITE_ROOT/"
  cp -u "$ASSETS_DIR/favicon-16x16.png" "$SITE_ROOT/"
  cp -u "$ASSETS_DIR/apple-touch-icon.png" "$SITE_ROOT/"
  cp -u "$ASSETS_DIR/site.webmanifest" "$SITE_ROOT/"
fi

# Check if the file already contains a favicon link
if grep -q 'rel="icon"' "$INDEX_FILE"; then
  echo "Favicons already present in $INDEX_FILE, skipping injection."
  exit 0
fi

# Insert favicon links before </head>
sed -i '/<\/head>/ i \
<link rel="icon" href="/favicon.ico" type="image/x-icon">\
<link rel="icon" href="/favicon-32x32.png" sizes="32x32" type="image/png">\
<link rel="icon" href="/favicon-16x16.png" sizes="16x16" type="image/png">\
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\
<link rel="manifest" href="/site.webmanifest">\
<meta name="theme-color" content="#ffffff">' "$INDEX_FILE"

echo "Favicons injected into $INDEX_FILE and copied to site root."