#import "../../index.typ": template, tufted, picture, article-heading
#show: template.with(title: "3DEO Processing Performance Report")

#article-heading()[Internship with 3DEO---Processing Performance Report][September 13, 2026]
#picture(image("imgs/cover.png", width: 75%))

#html.div(class: "introduction")[
  See #link("/posts/2025/internship-3deo")[3DEO internship overview] and slides from my internship presentation on #link("https://github.com/mward19/3deo-internship-presentation/tree/master")[GitHub].

  Also see example processing reports: #link("/assets/2025/processing_report_mapping.pdf")[Mapping Report], #link("/assets/2025/processing_report.pdf")[Single Tile Report]. (These are from the time of my internship presentation. Current reports contain further improvements)
]
#html.hr()

#set image(width: 100%)
= Processing Performance Report
Evaluating the success of a 3DEO lidar processing run is difficult. Diagnosing problems often requires digging through a SQL database with thousands of Slurm jobs, inspecting huge point clouds, parsing log files, and piecing together plots from different stages. It’s also important to know how long each stage took to identify bottlenecks. To streamline this process, 3DEO asked me to develop a tool that automatically generates human-readable processing performance reports.

#html.hr()

#picture(image("imgs/main-07.png"))

I chose to generate the report in a few steps. First, my program collects data from processing outputs and the SQL database of Slurm jobs. Then it compiles that information into a large JSON, which it uses to populate fields in a number of LaTeX templates I wrote. Finally, it generates a PDF from the LaTeX.

#html.hr()

#picture(image("imgs/main-08.png"))

3DEO's processing pipeline is designed to handle both small and large amounts of data. As such, the report must be very flexible. Some reports are just a few pages, while others are longer than many college textbooks. 

#html.hr()

Here are a couple reports generated by the program as it was at the end of July:
- #link("/assets/2025/documents/processing_report_mapping.pdf")[Mapping Report] (long)
- #link("/assets/2025/documents/processing_report.pdf")[Single Tile Report] (short)

Since generating these reports, based on my recollection (as I no longer have access to my code), additions and changes to the report include:
- Removal of unimplemented fields (like those in the per-tile registration section)
- Reports on processing errors, both in the overview and the per-tile sections
- Improved formatting of tile images
- Report" on versions of each processing module
- Per-tile processing timeline plot in each per-tile section

#html.hr()

#picture(image("imgs/main-10.png"))

The report begins with an overview of all processing performed in the run. It contains a number of useful visualizations focused on processing time, among other things.

#html.hr()

#picture(image("imgs/main-12.png"))

One such visualization is the Processing Timeline. It shows how long in real time (as opposed to CPU time) each stage of processing took. 

#picture(image("imgs/main-13.png"))

Each thread shows how long one Slurm job took.

#picture(image("imgs/main-14.png"))

When processing multiple targets (tiles) simultaneously, the vertical axis (within each processing module row) indicates which target each Slurm job corresponds to. This helps visualize how many jobs were running concurrently at any given time.

#html.hr()

#picture(image("imgs/main-15.png"))

The per-target (per-tile) sections of the report give detailed information for evaluating how successfully each target was processed. Since 3DEO currently processes targets individually, these sections help highlight issues or successes for specific tiles. One important subsection tracks data rejection, for which I modified the pipeline to record data rejections as they occurred during processing.

#html.hr()

Developing the processing performance report program gave me a deeper understanding of lidar data processing and challenged me to present complex technical information clearly. The resulting reports make it easier to monitor processing performance, identify bottlenecks, and address issues quickly, providing great practical value to the team and giving me a meaningful opportunity to explore 3DEO's advanced data processing tools.